[providers.python]
version = "3.9"

[providers.nodejs]
version = "18"

[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip', 'nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
    'python --version',
    'pip --version',
    'cd backend && pip install -r requirements.txt',
    'cd frontend && npm install'
]

[phases.build]
cmds = [
    'cd frontend && npm run build',
    'mkdir -p backend/static',
    'cp -r frontend/build/* backend/static/ 2>/dev/null || echo "No build files to copy"'
]

[start]
cmd = 'cd backend && python -m uvicorn server:app --host 0.0.0.0 --port $PORT'
